# Generated by Django 4.2.2 on 2023-06-30 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('cylinder', models.IntegerField()),
                ('max_weight', models.IntegerField()),
                ('max_speed', models.IntegerField()),
            ],
        ),
    ]
