# Generated by Django 4.2.2 on 2023-07-08 04:23

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tailgatetailliftbox_tailgatetailliftproduct_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tailgatetailliftproduct',
            old_name='Box',
            new_name='box',
        ),
        migrations.CreateModel(
            name='TreeNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app.treenode')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
