# Generated by Django 4.2.2 on 2023-07-08 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_coolingsystem_dumphoist_logisticproducts_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coolingsystem',
            options={'ordering': ['tree_id']},
        ),
        migrations.AlterModelOptions(
            name='dumphoist',
            options={'ordering': ['tree_id']},
        ),
        migrations.AlterModelOptions(
            name='logisticproducts',
            options={'ordering': ['tree_id']},
        ),
        migrations.AlterModelOptions(
            name='tailgatetaillift',
            options={'ordering': ['tree_id']},
        ),
    ]
