# Generated by Django 4.2.2 on 2023-07-08 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_coolingsystem_options_alter_dumphoist_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LogisticProducts',
            new_name='LogisticProduct',
        ),
    ]
