# Generated by Django 4.2.2 on 2023-07-11 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_logisticproducts_logisticproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image_src', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='AccessoriesStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote', models.BooleanField()),
                ('aluminium_gate', models.BooleanField()),
                ('short_gate', models.BooleanField()),
                ('long_gate', models.BooleanField()),
                ('two_fold_gate', models.BooleanField()),
                ('three_fold_gate', models.BooleanField()),
                ('wheel_protector', models.BooleanField()),
                ('plate', models.BooleanField()),
                ('more_cylinder', models.BooleanField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tailgatetaillift')),
            ],
        ),
    ]
