# Generated by Django 4.2.2 on 2023-07-11 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_accessory_accessoriesstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessoriesstatus',
            old_name='plate',
            new_name='metal_plate',
        ),
    ]
