# Generated by Django 4.2.2 on 2023-07-13 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_plate_accessoriesstatus_metal_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessoriesstatus',
            name='aluminium_gate',
            field=models.BooleanField(verbose_name='Aluminium Gate'),
        ),
        migrations.AlterField(
            model_name='accessoriesstatus',
            name='long_gate',
            field=models.BooleanField(verbose_name='Long Gate'),
        ),
        migrations.AlterField(
            model_name='accessoriesstatus',
            name='metal_plate',
            field=models.BooleanField(verbose_name='Metal Plate'),
        ),
        migrations.AlterField(
            model_name='accessoriesstatus',
            name='more_cylinder',
            field=models.BooleanField(verbose_name='More Cylinder'),
        ),
        migrations.AlterField(
            model_name='accessoriesstatus',
            name='remote',
            field=models.BooleanField(verbose_name='Remote'),
        ),
        migrations.AlterField(
            model_name='accessoriesstatus',
            name='short_gate',
            field=models.BooleanField(verbose_name='Short Gate'),
        ),
        migrations.AlterField(
            model_name='accessoriesstatus',
            name='three_fold_gate',
            field=models.BooleanField(verbose_name='Three Fold Gate'),
        ),
        migrations.AlterField(
            model_name='accessoriesstatus',
            name='two_fold_gate',
            field=models.BooleanField(verbose_name='Two Fold Gate'),
        ),
        migrations.AlterField(
            model_name='accessoriesstatus',
            name='wheel_protector',
            field=models.BooleanField(verbose_name='Wheel Protector'),
        ),
    ]
